{
  "contest": 143,
  "handle": "jayfromthe13th",
  "address": "0x47522595113c48db04ae640a9e499749b8414e88",
  "risk": "2",
  "title": "DOS(Denial Of Service).External calls can fail accidentally or deliberately, which can cause a DoS condition in the contract. ",
  "issueId": 363,
  "issueUrl": "https://github.com/code-423n4/2022-07-juicebox-findings/issues/363"
}